# Generated by Django 4.2 on 2023-12-12 14:58

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Artwork",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "create_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date when the artwork was created.",
                        verbose_name="Create Date",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The title of the artwork.",
                        max_length=255,
                        null=True,
                        verbose_name="Title",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        null=True, verbose_name="Description"
                    ),
                ),
                (
                    "image",
                    cloudinary.models.CloudinaryField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Image",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("painting", "Painting"),
                            ("sculpture", "Sculpture"),
                            ("photography", "Photography"),
                            ("posters", "Posters"),
                            ("portraits", "Portraits"),
                            ("contemporary", "Contemporary"),
                            ("abstract", "Abstract"),
                            ("popart", "Popart"),
                            ("classical", "Classical"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "approved",
                    models.BooleanField(
                        default=False, verbose_name="Approved"
                    ),
                ),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "auction_start",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "auction_duration",
                    models.CharField(
                        choices=[
                            ("3_days", "3 Days"),
                            ("7_days", "7 Days"),
                            ("10_days", "10 Days"),
                        ],
                        default="3_days",
                        max_length=8,
                    ),
                ),
                (
                    "reserve_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The minimum price at which the artwork can be sold.",
                        max_digits=10,
                        null=True,
                        verbose_name="Reserve Price",
                    ),
                ),
            ],
            options={
                "ordering": ["-create_date"],
            },
        ),
        migrations.CreateModel(
            name="Auction",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "create_date",
                    models.DateTimeField(
                        help_text="The date when the auction was created.",
                        null=True,
                        verbose_name="Create Date",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("closed", "Closed"),
                            ("cancelled", "Cancelled"),
                            ("pending", "Pending"),
                        ],
                        default="pending",
                        help_text="The current status of the auction.",
                        max_length=255,
                        null=True,
                        verbose_name="Status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        null=True, verbose_name="Is Active"
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        help_text="The date when the auction ends.",
                        null=True,
                        verbose_name="End Date",
                    ),
                ),
                (
                    "reserve_price",
                    models.IntegerField(
                        help_text="The minimum price at which the artwork can be sold.",
                        null=True,
                        verbose_name="Reserve Price",
                    ),
                ),
                (
                    "artwork",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auctions",
                        to="uptowngallery.artwork",
                        verbose_name="Artwork",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the user.",
                        max_length=255,
                        null=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "shipping_address",
                    models.CharField(
                        help_text="The shipping address of the user.",
                        max_length=255,
                        null=True,
                        verbose_name="Shipping Address",
                    ),
                ),
                (
                    "create_date",
                    models.DateTimeField(
                        help_text="The date when the user profile was created.",
                        null=True,
                        verbose_name="Create Date",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        help_text="Format: Required, Unique",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Bids",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "amount",
                    models.IntegerField(
                        help_text="The amount of the bid.",
                        null=True,
                        verbose_name="Amount",
                    ),
                ),
                (
                    "bid_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="The date and time when the bid was placed.",
                        verbose_name="Bid Time",
                    ),
                ),
                (
                    "auction",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="uptowngallery.auction",
                        verbose_name="Auction",
                    ),
                ),
                (
                    "bidder",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="uptowngallery.userprofile",
                        verbose_name="Bidder",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="artwork",
            name="artist",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="uptowngallery.userprofile",
                verbose_name="Artist",
            ),
        ),
    ]
