# Generated by Django 4.2 on 2023-12-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uptowngallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='auction_duration',
            field=models.CharField(choices=[('3', '3 days'), ('5', '5 days'), ('7', '7 days')], default='3_days', max_length=8),
        ),
    ]
