# Generated by Django 4.2 on 2023-12-13 15:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('uptowngallery', '0003_alter_artwork_auction_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The date when the artwork was created.', verbose_name='Create Date'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The date when the auction was created.', verbose_name='Create Date'),
        ),
    ]
