# Generated by Django 3.2.22 on 2023-11-18 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uptowngallery', '0004_artwork_approval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
