# Generated by Django 4.2 on 2023-12-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uptowngallery', '0005_alter_userprofile_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='duration',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
