# Generated by Django 4.2 on 2023-12-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uptowngallery', '0006_userprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='title',
            field=models.CharField(help_text='The title of the artwork.', max_length=255, null=True, verbose_name='Title'),
        ),
    ]
