# Generated by Django 4.2 on 2023-12-11 12:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('uptowngallery', '0007_artwork_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='bid_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The date and time when the bid was placed.', verbose_name='Bid Time'),
        ),
    ]
