# Generated by Django 4.2 on 2024-01-01 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uptowngallery', '0007_alter_bids_auction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
