# Generated by Django 4.2 on 2024-01-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uptowngallery', '0008_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='The amount of the bid in format 0.00.', max_digits=10, verbose_name='Amount'),
            preserve_default=False,
        ),
    ]
