# Generated by Django 4.2 on 2023-12-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uptowngallery', '0008_alter_bids_bid_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('cancelled', 'Cancelled'), ('pending', 'Pending')], default='pending', help_text='The current status of the auction.', max_length=255, null=True, verbose_name='Status'),
        ),
    ]
