# Generated by Django 4.2 on 2023-12-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uptowngallery', '0009_alter_auction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='auction_duration',
            field=models.CharField(choices=[('3_days', '3 Days'), ('7_days', '7 Days'), ('10_days', '10 Days')], default='3_days', max_length=8),
        ),
    ]
