# Generated by Django 4.2 on 2024-04-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uptowngallery', '0010_alter_artwork_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='auction_duration',
            field=models.CharField(choices=[('3', '3 days'), ('5', '5 days'), ('7', '7 days'), ('30', '30 days'), ('60', '60 days')], default='3', max_length=8),
        ),
    ]
