# Generated by Django 4.2 on 2023-12-12 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uptowngallery', '0010_artwork_auction_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='artwork',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to='uptowngallery.artwork', verbose_name='Artwork'),
        ),
    ]
